FROM python:3.12-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
PYTHONUNBUFFERED=1

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=pt_BR.UTF-8
ENV LANGUAGE=pt_BR:pt
ENV LC_ALL=pt_BR.UTF-8
ENV TZ="America/Manaus"

RUN export LANG=C.UTF-8
RUN set -eux; \
     apt-get update; \
     BASE="locales vim git build-essential cron ntpdate openssl curl qpdf tmpreaper"; \
     LDAP="libldap2-dev libsasl2-dev"; \
     PILLOW="libjpeg-dev libfreetype6-dev zlib1g-dev"; \
     PYMSSQL="freetds-dev"; \
     LXML="libxmlsec1-dev libxml2-dev libxslt1-dev"; \
     WEASYPRINT="libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz-subset0"; \
     apt-get install -y $BASE $LDAP $PILLOW $PYMSSQL $LXML $WEASYPRINT; \
     rm -rf /var/lib/apt/lists/*; rm -rf /var/cache/*;
RUN echo "pt_BR.UTF-8 UTF-8" >> /etc/locale.gen
RUN locale-gen pt_BR.UTF-8




WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    curl \
    postgresql-client \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY . .    

RUN uv pip install -r requirements.txt --system

EXPOSE 8000

CMD ["/app/docker/scripts/entrypoint.sh"]